### ISSUE TITLE
There is no code.

### ISSUE THREAD

**Issue by efindus** [Spaghetti1337/Gandalf#1]
Hello. Today I wanted to explore your repo and I found a terrible issue. There is no code there. Please fix this issue ASAP. Thanks in advance.

**Comment by efindus** [comment]
OK. The issue is solved.

**Comment by efindus** [comment]
Sadly lack of code is still an issue. There is no src/AI.js file. I hope you can find quick solution! Thanks in advance!

**Comment by Spaghetti1337** [comment]
fixed

**Comment by efindus** [comment]
https://github.com/lucleray/object-detection
Last lacking pieceof code.
